### ISSUE TITLE
A few nix issues

### ISSUE THREAD

**Issue by teh** [awakenetworks/gRPC-haskell#7]
Hey, first thanks so much for releasing this! I gave it a try and I ran into a few issues:

* release.nix uses `fetchgitPrivate` which fails because I don't have any keys exported
* cython fails, I think it should be `pkgs.pythonPackages.buildPythonPackage`?
* proto3-wire fails with [1] on nix-unstable. Which nix release are you using?

[1]
```
Setup: Encountered missing dependencies:
QuickCheck ==2.8.*
```

**Comment by teh** [comment]
thanks! Also a typo in the readme:

```
nix-shell release-nix -A grpc-haskell.env
```

should probably be (with a dot instead of a -):

```
nix-shell release.nix -A grpc-haskell.env
```

**Comment by intractable** [comment]
Hi @teh, please see [PR#8](https://github.com/awakenetworks/gRPC-haskell/pull/8), which I just merged. It pins `nixpkgs` to the correct revision and removes the use of `fetchgitPrivate`. 

Please let us know if you run into any problems building and running tests after these fixes. Thanks!

**Comment by teh** [comment]
It's working, thanks! Closing.
